/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        sans: ["PlusJakartaSans_400Regular"],
        "sans-medium": ["PlusJakartaSans_500Medium"],
        "sans-semibold": ["PlusJakartaSans_600SemiBold"],
        "sans-bold": ["PlusJakartaSans_700Bold"],
        display: ["Outfit_600SemiBold"],
        "display-bold": ["Outfit_700Bold"],
      },
      colors: {
        background: "var(--color-background)",
        surface: {
          DEFAULT: "var(--color-surface)",
          muted: "var(--color-surface-muted)",
          elevated: "var(--color-surface-elevated)",
          inset: "var(--color-surface-inset)",
        },
        foreground: {
          DEFAULT: "var(--color-text-primary)",
          secondary: "var(--color-text-secondary)",
          tertiary: "var(--color-text-tertiary)",
          inverse: "var(--color-text-inverse)",
          onAccent: "var(--color-text-on-accent)",
        },
        border: {
          DEFAULT: "var(--color-border-default)",
          subtle: "var(--color-border-subtle)",
          focus: "var(--color-border-focus)",
        },
        accent: {
          DEFAULT: "var(--color-accent)",
          bright: "var(--color-accent-bright)",
          muted: "var(--color-accent-muted)",
          soft: "var(--color-accent-soft)",
          glow: "var(--color-accent-glow)",
          hover: "var(--color-accent-hover)",
        },
        warm: {
          highlight: "var(--color-warm-highlight)",
        },
        delta: {
          up: "var(--color-delta-up)",
          "up-bg": "var(--color-delta-up-bg)",
          down: "var(--color-delta-down)",
          "down-bg": "var(--color-delta-down-bg)",
          "neutral-bg": "var(--color-delta-neutral-bg)",
        },
        overlay: "var(--color-overlay)",
        status: {
          processing: {
            DEFAULT: "var(--status-processing-fg)",
            bg: "var(--status-processing-bg)",
          },
          review: {
            DEFAULT: "var(--status-review-fg)",
            bg: "var(--status-review-bg)",
          },
          ready: {
            DEFAULT: "var(--status-ready-fg)",
            bg: "var(--status-ready-bg)",
          },
          failed: {
            DEFAULT: "var(--status-failed-fg)",
            bg: "var(--status-failed-bg)",
          },
        },
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
          6: "var(--chart-6)",
          7: "var(--chart-7)",
          8: "var(--chart-8)",
        },
      },
      spacing: {
        0: "0px",
        0.5: "2px",
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "32px",
        8: "40px",
        9: "48px",
        10: "64px",
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
        full: "9999px",
      },
      fontSize: {
        "display-hero": ["48px", { lineHeight: "52px", fontWeight: "700" }],
        "display-xl": ["40px", { lineHeight: "44px", fontWeight: "600" }],
        "display-lg": ["34px", { lineHeight: "40px", fontWeight: "600" }],
        "title-lg": ["26px", { lineHeight: "32px", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "24px", fontWeight: "400" }],
        body: ["16px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["15px", { lineHeight: "21px", fontWeight: "400" }],
        label: ["14px", { lineHeight: "20px", fontWeight: "600" }],
        caption: ["13px", { lineHeight: "18px", fontWeight: "500" }],
        micro: ["11px", { lineHeight: "16px", fontWeight: "500" }],
      },
      boxShadow: {
        card: "var(--shadow-card)",
        raised: "var(--shadow-raised)",
        floating: "var(--shadow-floating)",
        fab: "var(--shadow-fab)",
        sheet: "0px 12px 32px rgba(28, 25, 23, 0.14)",
      },
      letterSpacing: {
        tight: "-0.5px",
        wide: "0.4px",
      },
    },
  },
  plugins: [],
};
